apiVersion: v1
kind: ConfigMap
metadata:
  name: airline-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_NAME: "airline_db"
  DB_USER: "airline_user"
  DB_HOST: "db-service"
  DB_PORT: "5432"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173" 
